### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by ana-pfeilsticker** [unb-mds/2024-1-squad04#10]
De acordo com o levantamento de requisitos, serão criados os user stories para facilitar a criação do protótipo posteriormente.

**Comment by vitor-hoffmann** [comment]
User stories foram criados em um google doc
Link para o documento: https://docs.google.com/document/d/1cg6Xzp--MOIZkkQnOZ4-MX-LEOgZquHGY8BGq87swUE/edit#heading=h.p3aeyfhgb5md
