### ISSUE TITLE
Escolha de cores e tipografia

### ISSUE THREAD

**Issue by ana-pfeilsticker** [unb-mds/2024-1-squad04#11]
Escolha das cores e tipografia do sistema para o desenvolvimento do protótipo.

**Comment by leticiatmartins** [comment]
# Tipografia

- **Open Sans**: Títulos
- **Inter**: Textos

# Cores
A paleta de cores inclui tons de **verde (008E4A)**, **azul Escuro (102C46)**, **cinza (102C46)**, **azul claro (A9C5FC)** e **Branco puro (FFFFFF)** transmitindo confiança, crescimento e pertencimento à instituição.

**Comment by ana-pfeilsticker** [comment]
Top!
