### ISSUE TITLE
Documento de ideação

### ISSUE THREAD

**Issue by ana-pfeilsticker** [unb-mds/2024-1-squad04#14]
Pesquisa dos softwares com propósito semelhante ao Avalia Unb para analisar pontos de possível melhora.

**Comment by mtsmgn0** [comment]
### observações
encontramos um projeto anterior que ja cumpria o proposito da plataforma de maneira semelhante ao que pretendemos fazer. Mesmo assim, pretendemos refazer tudo do zero, e melhorar diversos fatores, tais como funcionalidades e interfaces gráficas
