### ISSUE TITLE
Protótipo figma - Login

### ISSUE THREAD

**Issue by leticiatmartins** [unb-mds/2024-1-squad04#17]
**Descrição**

- Eu como: Usuário
- Desejo: autenticar-me
- Para: poder ter acesso ao o Avalia UnB

**Comment by ana-pfeilsticker** [comment]
Protótipo de login concluído! 
![Entrar](https://github.com/unb-mds/2024-1-squad04/assets/110688069/542f420b-fed5-4827-b789-2d1ab5677c7b)
