### ISSUE TITLE
Protótipo figma - Cadastro

### ISSUE THREAD

**Issue by leticiatmartins** [unb-mds/2024-1-squad04#18]
### FT01 - Cadastro de Usuário
**Descrição:** Esta feature permite que novos usuários se cadastrem no sistema, fornecendo informações básicas e verificando a validade do e-mail.
### User Stories para FT01 - Cadastro de Usuário

| **User Story ID** | **Nome da História**       | **Descrição**                                                                                                      | **Critérios de Aceitação**                                                                                                          |
|-------------------|----------------------------|-------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| US01              | Cadastro de Usuário        | Como um usuário, eu quero poder me cadastrar no sistema para ter acesso às funcionalidades disponíveis.            | 1. Deve haver um formulário de cadastro com os campos: nome, sobrenome, e-mail, senha, confirmação de senha, matrícula e curso.<br>2. Deve verificar se o e-mail é válido.<br>3. Deve enviar um e-mail de confirmação para o usuário. |

**Comment by ana-pfeilsticker** [comment]
Página de cadastro prototipada, deverá ser desenvolvida pelo pessoal do front-end
![SINGUP avalia unb](https://github.com/unb-mds/2024-1-squad04/assets/110688069/4b88e1e3-8b27-4f55-97d1-7d5f3344d82f)
