### ISSUE TITLE
Página individual dos professores (back-end) 

### ISSUE THREAD

**Issue by Atyrson** [unb-mds/2024-1-squad04#37]
#### Descrição

Como desenvolvedor responsável pelo back-end,
Quero implementar a lógica necessária para fornecer informações detalhadas sobre professores específicos na página individual de professores, permitindo que os usuários visualizem dados como nome, faculdade, contato (e-mail), sala do professor, formação acadêmica, avaliação geral e avaliações feitas por alunos.

#### Critérios de Aceitação

| **Critério ID** | **Descrição**                                                                                         |
|-----------------|-------------------------------------------------------------------------------------------------------|
| CA01            | Desenvolver endpoints API para recuperar informações detalhadas de professores, incluindo nome, faculdade, contato, sala, formação acadêmica e outras informações relevantes. |
| CA02            | Implementar a integração com o banco de dados para recuperar e persistir os dados dos professores de forma eficiente. |
| CA03            | Incluir endpoints para recuperar a avaliação geral de cada professor, calculada com base nas avaliações individuais de acesso, didática, metodologia e carisma. |
| CA04            | Permitir aos usuários acessar e visualizar as avaliações feitas pelos alunos sobre cada professor, incluindo comentários, estrelas atribuídas e interações (curtidas e descurtidas). |
| CA05            | Garantir que apenas os usuários autenticados possam acessar e interagir com as avaliações dos professores. |

#### Features

| **Feature ID** | **Descrição**                                                                                     |
|----------------|---------------------------------------------------------------------------------------------------|
| F32            | Criar modelos de dados para armazenar informações detalhadas de professores, suas salas e faculdades. |
| F33            | Implementar serviços e controladores para manipular e recuperar dados dos professores e suas avaliações. |
| F34            | Desenvolver lógica para calcular e exibir a avaliação geral de cada professor com base nas avaliações individuais. |
| F35            | Configurar endpoints API para suportar operações de listagem e consulta das avaliações feitas pelos alunos sobre os professores. |

**Comment by ana-pfeilsticker** [comment]
Backend completo, merge dado!
