### ISSUE TITLE
Avaliação de professores pop-up (back-end)

### ISSUE THREAD

**Issue by Atyrson** [unb-mds/2024-1-squad04#39]
#### Descrição

Como desenvolvedor responsável pelo back-end,
Quero implementar a lógica necessária para processar as avaliações dos professores feitas pelos usuários através de um pop-up,
Para permitir  que os usuários atribuam estrelas e comentários sobre critérios como Acesso, Didática, Metodologia e Carisma.

#### Critérios de Aceitação

| **Critério ID** | **Descrição**                                                                                         |
|-----------------|-------------------------------------------------------------------------------------------------------|
| CA01            | Desenvolver endpoints API para receber e persistir as avaliações dos usuários sobre os professores, incluindo estrelas atribuídas para cada critério (Acesso, Didática, Metodologia, Carisma) e comentários . |
| CA02            | Validar os dados enviados pelos usuários para garantir integridade e segurança das avaliações.        |
| CA03            | Implementar a integração com o banco de dados para armazenar as avaliações dos professores de forma eficiente e segura. |
| CA04            | Garantir que cada usuário possa avaliar um professor apenas uma vez e apenas se estiver autenticado em sua conta. |

#### Features

| **Feature ID** | **Descrição**                                                                                     |
|----------------|---------------------------------------------------------------------------------------------------|
| F37            | Criar modelos de dados para armazenar avaliações de professores, incluindo estrelas e comentários para cada critério. |
| F38            | Implementar serviços e controladores para processar e persistir as avaliações recebidas através dos endpoints API. |
| F39            | Desenvolver lógica para verificar a autenticação do usuário antes de permitir o envio de avaliações. |
| F40            | Configurar endpoints API para suportar operações de criação e atualização das avaliações de professores. |

**Comment by vitor-hoffmann** [comment]
Implementado
