### ISSUE TITLE
RF06 - Login

### ISSUE THREAD

**Issue by ana-pfeilsticker** [unb-mds/2024-1-squad04#4]
# Login de usuário

### EP01 - Gestão de Usuários
**Descrição:** Este épico abrange todas as funcionalidades relacionadas à gestão de usuários no sistema, incluindo cadastro, autenticação, perfil e permissões.

### FT02 - Autenticação de Usuário
**Descrição:** Esta feature permite que os usuários façam login no sistema utilizando email e senha ou autenticação.

## User Stories

| **User Story ID** | **Nome da História**       | **Descrição**                                                                                                      | **Critérios de Aceitação**                                                                                                          |
|-------------------|----------------------------|-------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| US02              | Login de Usuário           | Como um usuário, eu quero fazer login no sistema usando meu email e senha ou autenticação  para acessar minhas informações pessoais. | 1. O sistema deve permitir login com email e senha.<br>2. Se a autenticação for bem-sucedida, o usuário deve ser redirecionado para sua página inicial.<br>3.O sistema deve verificar se o email para login é válido |

## Requisitos Funcionais

| **Requisito Funcional ID** | **Descrição**                                                                                                 |
|----------------------------|---------------------------------------------------------------------------------------------------------------|
| RF06                       |  |

**Comment by vitor-hoffmann** [comment]
Pagina de login implementada, testada e funcionando

**Comment by ana-pfeilsticker** [comment]
- Tirar o via Google, não teremos mais essa autenticação pelo google.
- O sistema deve verificar se o email para login é válido
