### ISSUE TITLE
Filtragem de professores por matérias

### ISSUE THREAD

**Issue by Atyrson** [unb-mds/2024-1-squad04#40]
#### Descrição

Como usuário interessado em encontrar professores específicos por matéria,
Quero ter a capacidade de filtrar os professores disponíveis de acordo com a disciplina que cada um leciona,
Para uma melhor visualização. 

#### Critérios de Aceitação

| **Critério ID** | **Descrição**                                                                                         |
|-----------------|-------------------------------------------------------------------------------------------------------|
| CA01            | Implementar um menu suspenso ou caixa de seleção na página de professores para escolha da disciplina. |
| CA02            | Ao selecionar uma disciplina, exibir apenas os professores que ministram essa disciplina.            |
| CA03            | Permitir ao usuário selecionar múltiplas disciplinas para refinar ainda mais a busca, se desejado.   |
| CA04            | Garantir que a aplicação dos filtros seja instantânea e responsiva, sem necessidade de recarregar a página. |

#### Features

| **Feature ID** | **Descrição**                                                                                     |
|----------------|---------------------------------------------------------------------------------------------------|
| F20            | Desenvolver um menu de seleção de disciplinas na página de professores.                            |
| F21            | Implementar a lógica de filtragem dinâmica para exibir apenas os professores das disciplinas selecionadas. |
| F22            | Oferecer suporte para seleção múltipla de disciplinas, se aplicável.                               |
| F23            | Garantir uma experiência de usuário fluida e responsiva durante a aplicação dos filtros.            |

#### Notas Adicionais

- Assegurar que a lista de disciplinas disponíveis para seleção esteja atualizada e seja fácil de navegar.
- Testar a funcionalidade em diferentes navegadores e dispositivos para garantir consistência.

**Comment by ana-pfeilsticker** [comment]
Merge feito!
