### ISSUE TITLE
Back-end página minhas avaliações 

### ISSUE THREAD

**Issue by leticiatmartins** [unb-mds/2024-1-squad04#48]
#### Descrição

Como desenvolvedor responsável pelo back-end,
Quero implementar a lógica necessária para coletar as informações dos comentários feitos pelos usuários sobre matérias e professores, de modo que essas informações possam ser exibidas na página "Minhas Avaliações" no front-end.

#### Critérios de Aceitação

| **Critério ID** | **Descrição**                                                                                         |
|-----------------|-------------------------------------------------------------------------------------------------------|
| CA01            | Desenvolver endpoints API para recuperar os comentários feitos pelo usuário, incluindo conteúdo do comentário, número de estrelas atribuídas, quantidade de curtidas e outras informações relevantes. |
| CA02            | Implementar a integração com o banco de dados para persistir e recuperar os comentários dos usuários de forma eficiente. |
| CA03            | Garantir que apenas o próprio usuário autenticado possa acessar e manipular seus próprios comentários. |
| CA04            | Realizar validações de segurança e integridade dos dados durante a inserção e recuperação dos comentários. |

#### Features

| **Feature ID** | **Descrição**                                                                                     |
|----------------|---------------------------------------------------------------------------------------------------|
| F28            | Criar modelos de dados adequados para armazenar comentários de usuários, associando-os corretamente a professores e matérias. |
| F29            | Implementar serviços e controladores para manipulação de comentários, incluindo operações de listagem, criação e exclusão. |
| F30            | Estabelecer rotinas de segurança para autenticação e autorização de usuários ao acessar seus próprios comentários. |
| F31            | Configurar a comunicação eficiente entre o back-end e o front-end para transferência de dados dos comentários. |

**Comment by ana-pfeilsticker** [comment]
# Lista de atividades

Aqui estão as features para concluir essa issue:

- [x] Alternar entre avaliações de matérias e avaliações de professores
- [x] Listar avaliações de matérias
- [x] Listar avaliações de professores
- [x] Deletar avaliações de professores
- [x] Deletar avaliações de matérias

**Comment by ana-pfeilsticker** [comment]
Finalizada!
